version: '3.4'

services:
  api:
    image: usuarios-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=usuarios;Password=123;Database=Usuarios
    depends_on:
      - db
    volumes:
      - ./userApp:/userApp

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Usuarios
      POSTGRES_USER: usuarios
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
